# Generated by Django 2.2.6 on 2019-10-11 20:25

from django.db import migrations, models
import django.db.models.deletion
import pubblicita.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, unique=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to=pubblicita.models.annuario_directory_path)),
                ('giuria', models.TextField(blank=True, null=True)),
                ('impaginazione', models.TextField(blank=True, max_length=200, null=True)),
                ('intro_title', models.TextField(blank=True, null=True)),
                ('intro_text', models.TextField(blank=True, null=True)),
                ('intro_footer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_nome', models.CharField(max_length=20, unique=True)),
                ('img', models.ImageField(upload_to=pubblicita.models.opera_directory_path)),
                ('annuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubblicita.Annuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soggetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cognome', models.CharField(blank=True, max_length=100, null=True)),
                ('citta', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOpera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubblicita.Annuario')),
                ('opera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubblicita.Opera')),
                ('ruolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pubblicita.Ruolo')),
                ('soggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubblicita.Soggetto')),
            ],
        ),
        migrations.AddField(
            model_name='opera',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubblicita.TipoOpera'),
        ),
        migrations.CreateModel(
            name='ImmaginiAnnuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('annuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubblicita.Annuario')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
